pr:
  branches:
    include:
    - main
    - feature/semver

resources:
  repositories:
  - repository: templates
    type: git
    name: 'Cloud Hosting Service/Templates'
    ref: 'feature/semver-increment-check'

stages:
- template: semver-increment-check.yml@templates