# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:
- name: forcePushToProd
  displayName: Force Push to Production
  type: boolean
  default: false

variables:
  buildMajor: 0
  buildMinor: 0
  buildBranch: $[replace(variables['Build.SourceBranch'], '/', '.')]

pool: "vmss-ado-chs-nonprod-001"
          
resources:
  repositories:
  - repository: he-ahofr-deployment
    type: git
    name: 'Find Affordable Homes/he-ahofr-deployment'
    ref: 'feature/semver'
  - repository: templates
    type: git
    name: 'Cloud Hosting Service/Templates'
    ref: 'master'

stages:
- template: azure-pipelines-build.yml@he-ahofr-deployment
  parameters:
    forcePushToProd: ${{ parameters.forcePushToProd }}
