# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr:
  branches:
    include:
    - main

schedules:
- cron: "09 14 * * Mon,Tue,Wed,Thu,Fri"
  displayName: Nightly Test Run
  branches:
    include:
    - feature/nightlies
  always: true
  
parameters:
- name: forcePushToProd
  displayName: Force Push to Production
  type: boolean
  default: false

variables:
  buildMajor: 1
  buildMinor: 1
  buildBranch: $[replace(variables['Build.SourceBranch'], '/', '.')]

pool: "vmss-ado-chs-nonprod-001"

name: $(buildMajor).$(buildMinor).$(Rev:r)-$(buildBranch)

resources:
  repositories:
  - repository: he-ahofr-deployment
    type: git
    name: 'Find Affordable Homes/he-ahofr-deployment'
    ref: 'feature/nightlies'
  - repository: templates
    type: git
    name: 'Cloud Hosting Service/Templates'
  

stages:
- template: azure-pipelines-build.yml@he-ahofr-deployment
  parameters:
    forcePushToProd: ${{ parameters.forcePushToProd }}
