# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'ubuntu-18.04'

resources:
  repositories:
  - repository: he-ahofr-deployment
    type: git
    name: 'Find Affrdable Homes/he-ahofr-deployment'   
    ref: 'main'
  - repository: templates
    type: git
    name: 'Find Affrdable Homes/Templates'   
    ref: 'master'

stages:
- template: azure-pipelines-1.yml@he-ahofr-deployment
