schedules:
- cron: "0 9 1 * *" 
  displayName: schedule - first of each month
  branches:
    include:
    - main
  always: true

trigger: none

resources:
  repositories:
    - repository: scripts
      type: git
      name: 'Cloud Hosting Service/chs-core-infrastructure'
      ref: 'feature/new-clean-repos'
    - repository: he-ahofr-deployment
      type: git
      name: 'Find Affordable Homes/he-ahofr-deployment'
      ref: 'feature/ado-clean-repos'

stages:
- template: clean-repos.yml@he-ahofr-deployment